In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("customer_churn_sample.csv")

In [3]:
df.head()

,CustomerID,Gender,Age,TenureMonths,SubscriptionType,MonthlyCharges,TotalCharges,ContractType,SupportTickets,PaymentMethod,Churn
0,CUST-1001,Female,34,12,Basic,49.99,599.88,Month-to-Month,3,Credit Card,Yes
1,CUST-1002,Male,45,24,Pro,79.99,1919.76,One Year,1,Bank Transfer,No
2,CUST-1003,Female,29,6,Basic,49.99,299.94,Month-to-Month,5,UPI,Yes
3,CUST-1004,Male,52,36,Enterprise,149.99,5399.64,Two Year,0,Credit Card,No
4,CUST-1005,Female,41,8,Pro,79.99,639.92,Month-to-Month,4,Debit Card,Yes

In [4]:
df

,CustomerID,Gender,Age,TenureMonths,SubscriptionType,MonthlyCharges,TotalCharges,ContractType,SupportTickets,PaymentMethod,Churn
0,CUST-1001,Female,34,12,Basic,49.99,599.88,Month-to-Month,3,Credit Card,Yes
1,CUST-1002,Male,45,24,Pro,79.99,1919.76,One Year,1,Bank Transfer,No
2,CUST-1003,Female,29,6,Basic,49.99,299.94,Month-to-Month,5,UPI,Yes
3,CUST-1004,Male,52,36,Enterprise,149.99,5399.64,Two Year,0,Credit Card,No
4,CUST-1005,Female,41,8,Pro,79.99,639.92,Month-to-Month,4,Debit Card,Yes
5,CUST-1006,Male,31,18,Basic,49.99,899.82,One Year,2,UPI,No
6,CUST-1007,Female,23,3,Basic,49.99,149.97,Month-to-Month,6,Credit Card,Yes
7,CUST-1008,Male,60,48,Enterprise,149.99,7199.52,Two Year,1,Bank Transfer,No
8,CUST-1009,Female,38,15,Pro,79.99,1199.85,One Year,2,Credit Card,No
9,CUST-1010,Male,27,4,Basic,49.99,199.96,Month-to-Month,4,UPI,Yes
10,CUST-1011,Female,49,30,Enterprise,149.99,4499.70,Two Year,0,Credit Card,No
11,CUST-1012,Male,33,14,Pro,79.99,1119.86,Month-to-Month,3,Debit Card,Yes
12,CUST-1013,Female,55,22,Basic,49.99,1099.78,One Year,1,Bank Transfer,No
13,CUST-1014,Male,26,2,Basic,49.99,99.98,Month-to-Month,5,UPI,Yes
14,CUST-1015,Female,43,40,Enterprise,149.99,5999.60,Two Year,1,Credit Card,No

In [5]:
df.shape

(15, 11)

In [6]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'TenureMonths', 'SubscriptionType',
       'MonthlyCharges', 'TotalCharges', 'ContractType', 'SupportTickets',
       'PaymentMethod', 'Churn'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        15 non-null     object
 1   Gender            15 non-null     object
 2   Age               15 non-null     int64
 3   TenureMonths      15 non-null     int64
 4   SubscriptionType  15 non-null     object
 5   MonthlyCharges    15 non-null     float64
 6   TotalCharges      15 non-null     float64
 7   ContractType      15 non-null     object
 8   SupportTickets    15 non-null     int64
 9   PaymentMethod     15 non-null     object
 10  Churn             15 non-null     object
dtypes: float64(2), int64(3), object(6)
memory usage: 1.4+ KB

In [8]:
df.isnull().sum()

CustomerID          0
Gender              0
Age                 0
TenureMonths        0
SubscriptionType    0
MonthlyCharges      0
TotalCharges        0
ContractType        0
SupportTickets      0
PaymentMethod       0
Churn               0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df.columns)

Index(['customerid', 'gender', 'age', 'tenuremonths', 'subscriptiontype',
       'monthlycharges', 'totalcharges', 'contracttype', 'supporttickets',
       'paymentmethod', 'churn'],
      dtype='object')

In [11]:
print(df["gender"].unique())
print(df["contracttype"].unique())
print(df["paymentmethod"].unique())
print(df["churn"].unique())

['Female' 'Male']
['Month-to-Month' 'One Year' 'Two Year']
['Credit Card' 'Bank Transfer' 'UPI' 'Debit Card']
['Yes' 'No']

In [12]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["tenuremonths"] = pd.to_numeric(df["tenuremonths"], errors="coerce")
df["monthlycharges"] = pd.to_numeric(df["monthlycharges"], errors="coerce")
df["totalcharges"] = pd.to_numeric(df["totalcharges"], errors="coerce")
df["supporttickets"] = pd.to_numeric(df["supporttickets"], errors="coerce")

In [13]:
df.isnull().sum()

customerid          0
gender              0
age                 0
tenuremonths        0
subscriptiontype    0
monthlycharges      0
totalcharges        0
contracttype        0
supporttickets      0
paymentmethod       0
churn               0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        15 non-null     object
 1   gender            15 non-null     object
 2   age               15 non-null     int64
 3   tenuremonths      15 non-null     int64
 4   subscriptiontype  15 non-null     object
 5   monthlycharges    15 non-null     float64
 6   totalcharges      15 non-null     float64
 7   contracttype      15 non-null     object
 8   supporttickets    15 non-null     int64
 9   paymentmethod     15 non-null     object
 10  churn             15 non-null     object
dtypes: float64(2), int64(3), object(6)
memory usage: 1.4+ KB

In [16]:
df.to_csv("cleaned_customer_churn.csv", index=False)